name: Deploy RUE

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_RUE }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_RUE }}
